console.log("BEFORE INITIALIZATION");
var bankName;
console.log("Bank Name:",bankName);
console.log("Data Type",typeof bankName);
console.log("AFTER INITIALIZATION");
var bankName = 'SBI Bank';
console.log("Bank Name:", bankName);
console.log("Data Type:",typeof bankName);
console.log("------------------------------------------------------------------------");
var marks =' 90%' ;
console.log("Marks:",marks);
console.log("Data Type:",typeof marks);
console.log("-------------------------------------------------------------------------");
console.log("BEFORE INITIALIZATION");
var isWorking;
console.log("value:",isWorking);
console.log("AFTER INITIALIZATION");
var isWorking = true;
console.log("Value:",isWorking);
console.log("Data Type:",typeof isWorking);
console.log("---------------------------------------------------------------------------");
var totalCount = "Hundred and Seven";
console.log("Value:",totalCount);
console.log("Data Type:",typeof totalCount);
var totalCount = 107;
console.log("Value:",totalCount);
console.log("Data Type:",typeof totalCount);
console.log("----------------------------------------------------------------------------");

